// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: teov1/runs.proto

package teov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRunRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RepoFullName    string                 `protobuf:"bytes,1,opt,name=repo_full_name,json=repoFullName,proto3" json:"repo_full_name,omitempty"`
	CommitSha       string                 `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Branch          string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Manifest        *TestManifest          `protobuf:"bytes,4,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Budget          *RunBudget             `protobuf:"bytes,5,opt,name=budget,proto3" json:"budget,omitempty"`
	TriggerActor    string                 `protobuf:"bytes,6,opt,name=trigger_actor,json=triggerActor,proto3" json:"trigger_actor,omitempty"`
	TriggerPrNumber int32                  `protobuf:"varint,7,opt,name=trigger_pr_number,json=triggerPrNumber,proto3" json:"trigger_pr_number,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRunRequest) Reset() {
	*x = CreateRunRequest{}
	mi := &file_teov1_runs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunRequest) ProtoMessage() {}

func (x *CreateRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_runs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunRequest.ProtoReflect.Descriptor instead.
func (*CreateRunRequest) Descriptor() ([]byte, []int) {
	return file_teov1_runs_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRunRequest) GetRepoFullName() string {
	if x != nil {
		return x.RepoFullName
	}
	return ""
}

func (x *CreateRunRequest) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *CreateRunRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CreateRunRequest) GetManifest() *TestManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *CreateRunRequest) GetBudget() *RunBudget {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *CreateRunRequest) GetTriggerActor() string {
	if x != nil {
		return x.TriggerActor
	}
	return ""
}

func (x *CreateRunRequest) GetTriggerPrNumber() int32 {
	if x != nil {
		return x.TriggerPrNumber
	}
	return 0
}

func (x *CreateRunRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_teov1_runs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_runs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_teov1_runs_proto_rawDescGZIP(), []int{1}
}

func (x *GetRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_teov1_runs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_runs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_teov1_runs_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runner        string                 `protobuf:"bytes,1,opt,name=runner,proto3" json:"runner,omitempty"`
	Tests         []*TestEntry           `protobuf:"bytes,2,rep,name=tests,proto3" json:"tests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestManifest) Reset() {
	*x = TestManifest{}
	mi := &file_teov1_runs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestManifest) ProtoMessage() {}

func (x *TestManifest) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_runs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestManifest.ProtoReflect.Descriptor instead.
func (*TestManifest) Descriptor() ([]byte, []int) {
	return file_teov1_runs_proto_rawDescGZIP(), []int{3}
}

func (x *TestManifest) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

func (x *TestManifest) GetTests() []*TestEntry {
	if x != nil {
		return x.Tests
	}
	return nil
}

type TestEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParamsHash    string                 `protobuf:"bytes,3,opt,name=params_hash,json=paramsHash,proto3" json:"params_hash,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestEntry) Reset() {
	*x = TestEntry{}
	mi := &file_teov1_runs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestEntry) ProtoMessage() {}

func (x *TestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_runs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestEntry.ProtoReflect.Descriptor instead.
func (*TestEntry) Descriptor() ([]byte, []int) {
	return file_teov1_runs_proto_rawDescGZIP(), []int{4}
}

func (x *TestEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TestEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestEntry) GetParamsHash() string {
	if x != nil {
		return x.ParamsHash
	}
	return ""
}

func (x *TestEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RunBudget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxSeconds    int32                  `protobuf:"varint,1,opt,name=max_seconds,json=maxSeconds,proto3" json:"max_seconds,omitempty"`
	MaxWorkers    int32                  `protobuf:"varint,2,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunBudget) Reset() {
	*x = RunBudget{}
	mi := &file_teov1_runs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBudget) ProtoMessage() {}

func (x *RunBudget) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_runs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBudget.ProtoReflect.Descriptor instead.
func (*RunBudget) Descriptor() ([]byte, []int) {
	return file_teov1_runs_proto_rawDescGZIP(), []int{5}
}

func (x *RunBudget) GetMaxSeconds() int32 {
	if x != nil {
		return x.MaxSeconds
	}
	return 0
}

func (x *RunBudget) GetMaxWorkers() int32 {
	if x != nil {
		return x.MaxWorkers
	}
	return 0
}

type Run struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoFullName    string                 `protobuf:"bytes,2,opt,name=repo_full_name,json=repoFullName,proto3" json:"repo_full_name,omitempty"`
	CommitSha       string                 `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Branch          string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	TotalDurationMs int32                  `protobuf:"varint,8,opt,name=total_duration_ms,json=totalDurationMs,proto3" json:"total_duration_ms,omitempty"`
	BudgetSeconds   int32                  `protobuf:"varint,9,opt,name=budget_seconds,json=budgetSeconds,proto3" json:"budget_seconds,omitempty"`
	PreemptionCount int32                  `protobuf:"varint,10,opt,name=preemption_count,json=preemptionCount,proto3" json:"preemption_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_teov1_runs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_runs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_teov1_runs_proto_rawDescGZIP(), []int{6}
}

func (x *Run) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Run) GetRepoFullName() string {
	if x != nil {
		return x.RepoFullName
	}
	return ""
}

func (x *Run) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *Run) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Run) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Run) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Run) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Run) GetTotalDurationMs() int32 {
	if x != nil {
		return x.TotalDurationMs
	}
	return 0
}

func (x *Run) GetBudgetSeconds() int32 {
	if x != nil {
		return x.BudgetSeconds
	}
	return 0
}

func (x *Run) GetPreemptionCount() int32 {
	if x != nil {
		return x.PreemptionCount
	}
	return 0
}

var File_teov1_runs_proto protoreflect.FileDescriptor

const file_teov1_runs_proto_rawDesc = "" +
	"\n" +
	"\x10teov1/runs.proto\x12\x06teo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x02\n" +
	"\x10CreateRunRequest\x12$\n" +
	"\x0erepo_full_name\x18\x01 \x01(\tR\frepoFullName\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x02 \x01(\tR\tcommitSha\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x120\n" +
	"\bmanifest\x18\x04 \x01(\v2\x14.teo.v1.TestManifestR\bmanifest\x12)\n" +
	"\x06budget\x18\x05 \x01(\v2\x11.teo.v1.RunBudgetR\x06budget\x12#\n" +
	"\rtrigger_actor\x18\x06 \x01(\tR\ftriggerActor\x12*\n" +
	"\x11trigger_pr_number\x18\a \x01(\x05R\x0ftriggerPrNumber\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\"\x1f\n" +
	"\rGetRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10CancelRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\fTestManifest\x12\x16\n" +
	"\x06runner\x18\x01 \x01(\tR\x06runner\x12'\n" +
	"\x05tests\x18\x02 \x03(\v2\x11.teo.v1.TestEntryR\x05tests\"h\n" +
	"\tTestEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vparams_hash\x18\x03 \x01(\tR\n" +
	"paramsHash\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"M\n" +
	"\tRunBudget\x12\x1f\n" +
	"\vmax_seconds\x18\x01 \x01(\x05R\n" +
	"maxSeconds\x12\x1f\n" +
	"\vmax_workers\x18\x02 \x01(\x05R\n" +
	"maxWorkers\"\x80\x03\n" +
	"\x03Run\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0erepo_full_name\x18\x02 \x01(\tR\frepoFullName\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x03 \x01(\tR\tcommitSha\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12*\n" +
	"\x11total_duration_ms\x18\b \x01(\x05R\x0ftotalDurationMs\x12%\n" +
	"\x0ebudget_seconds\x18\t \x01(\x05R\rbudgetSeconds\x12)\n" +
	"\x10preemption_count\x18\n" +
	" \x01(\x05R\x0fpreemptionCount2\x9c\x01\n" +
	"\x04Runs\x122\n" +
	"\tCreateRun\x12\x18.teo.v1.CreateRunRequest\x1a\v.teo.v1.Run\x12,\n" +
	"\x06GetRun\x12\x15.teo.v1.GetRunRequest\x1a\v.teo.v1.Run\x122\n" +
	"\tCancelRun\x12\x18.teo.v1.CancelRunRequest\x1a\v.teo.v1.RunB3Z1github.com/teo-dev/teo/internal/proto/teov1;teov1b\x06proto3"

var (
	file_teov1_runs_proto_rawDescOnce sync.Once
	file_teov1_runs_proto_rawDescData []byte
)

func file_teov1_runs_proto_rawDescGZIP() []byte {
	file_teov1_runs_proto_rawDescOnce.Do(func() {
		file_teov1_runs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_teov1_runs_proto_rawDesc), len(file_teov1_runs_proto_rawDesc)))
	})
	return file_teov1_runs_proto_rawDescData
}

var file_teov1_runs_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_teov1_runs_proto_goTypes = []any{
	(*CreateRunRequest)(nil),      // 0: teo.v1.CreateRunRequest
	(*GetRunRequest)(nil),         // 1: teo.v1.GetRunRequest
	(*CancelRunRequest)(nil),      // 2: teo.v1.CancelRunRequest
	(*TestManifest)(nil),          // 3: teo.v1.TestManifest
	(*TestEntry)(nil),             // 4: teo.v1.TestEntry
	(*RunBudget)(nil),             // 5: teo.v1.RunBudget
	(*Run)(nil),                   // 6: teo.v1.Run
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_teov1_runs_proto_depIdxs = []int32{
	3, // 0: teo.v1.CreateRunRequest.manifest:type_name -> teo.v1.TestManifest
	5, // 1: teo.v1.CreateRunRequest.budget:type_name -> teo.v1.RunBudget
	4, // 2: teo.v1.TestManifest.tests:type_name -> teo.v1.TestEntry
	7, // 3: teo.v1.Run.started_at:type_name -> google.protobuf.Timestamp
	7, // 4: teo.v1.Run.finished_at:type_name -> google.protobuf.Timestamp
	0, // 5: teo.v1.Runs.CreateRun:input_type -> teo.v1.CreateRunRequest
	1, // 6: teo.v1.Runs.GetRun:input_type -> teo.v1.GetRunRequest
	2, // 7: teo.v1.Runs.CancelRun:input_type -> teo.v1.CancelRunRequest
	6, // 8: teo.v1.Runs.CreateRun:output_type -> teo.v1.Run
	6, // 9: teo.v1.Runs.GetRun:output_type -> teo.v1.Run
	6, // 10: teo.v1.Runs.CancelRun:output_type -> teo.v1.Run
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_teov1_runs_proto_init() }
func file_teov1_runs_proto_init() {
	if File_teov1_runs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_teov1_runs_proto_rawDesc), len(file_teov1_runs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teov1_runs_proto_goTypes,
		DependencyIndexes: file_teov1_runs_proto_depIdxs,
		MessageInfos:      file_teov1_runs_proto_msgTypes,
	}.Build()
	File_teov1_runs_proto = out.File
	file_teov1_runs_proto_goTypes = nil
	file_teov1_runs_proto_depIdxs = nil
}
