// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: teov1/workers.proto

package teov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Runner        string                 `protobuf:"bytes,2,opt,name=runner,proto3" json:"runner,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	CapacityType  string                 `protobuf:"bytes,4,opt,name=capacity_type,json=capacityType,proto3" json:"capacity_type,omitempty"` // spot | on_demand | unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_teov1_workers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_workers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_teov1_workers_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetCapacityType() string {
	if x != nil {
		return x.CapacityType
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           string                 `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_teov1_workers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_workers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_teov1_workers_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_teov1_workers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_workers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_teov1_workers_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_teov1_workers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_workers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_teov1_workers_proto_rawDescGZIP(), []int{3}
}

type PullAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Runner        string                 `protobuf:"bytes,2,opt,name=runner,proto3" json:"runner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullAssignmentRequest) Reset() {
	*x = PullAssignmentRequest{}
	mi := &file_teov1_workers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullAssignmentRequest) ProtoMessage() {}

func (x *PullAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_workers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullAssignmentRequest.ProtoReflect.Descriptor instead.
func (*PullAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_teov1_workers_proto_rawDescGZIP(), []int{4}
}

func (x *PullAssignmentRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PullAssignmentRequest) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

type Assignment struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ShardId             string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	RunId               string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	RepoFullName        string                 `protobuf:"bytes,3,opt,name=repo_full_name,json=repoFullName,proto3" json:"repo_full_name,omitempty"`
	Tests               []*TestEntryRef        `protobuf:"bytes,4,rep,name=tests,proto3" json:"tests,omitempty"`
	PredictedDurationMs int32                  `protobuf:"varint,5,opt,name=predicted_duration_ms,json=predictedDurationMs,proto3" json:"predicted_duration_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_teov1_workers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_workers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_teov1_workers_proto_rawDescGZIP(), []int{5}
}

func (x *Assignment) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *Assignment) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Assignment) GetRepoFullName() string {
	if x != nil {
		return x.RepoFullName
	}
	return ""
}

func (x *Assignment) GetTests() []*TestEntryRef {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *Assignment) GetPredictedDurationMs() int32 {
	if x != nil {
		return x.PredictedDurationMs
	}
	return 0
}

type TestEntryRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParamsHash    string                 `protobuf:"bytes,3,opt,name=params_hash,json=paramsHash,proto3" json:"params_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestEntryRef) Reset() {
	*x = TestEntryRef{}
	mi := &file_teov1_workers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestEntryRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestEntryRef) ProtoMessage() {}

func (x *TestEntryRef) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_workers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestEntryRef.ProtoReflect.Descriptor instead.
func (*TestEntryRef) Descriptor() ([]byte, []int) {
	return file_teov1_workers_proto_rawDescGZIP(), []int{6}
}

func (x *TestEntryRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TestEntryRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestEntryRef) GetParamsHash() string {
	if x != nil {
		return x.ParamsHash
	}
	return ""
}

type TestFinished struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShardId        string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	RunId          string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TestPath       string                 `protobuf:"bytes,3,opt,name=test_path,json=testPath,proto3" json:"test_path,omitempty"`
	TestName       string                 `protobuf:"bytes,4,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	ParamsHash     string                 `protobuf:"bytes,5,opt,name=params_hash,json=paramsHash,proto3" json:"params_hash,omitempty"`
	Attempt        int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Outcome        string                 `protobuf:"bytes,7,opt,name=outcome,proto3" json:"outcome,omitempty"`
	DurationMs     int32                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	FailureMessage string                 `protobuf:"bytes,9,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	FailureStack   string                 `protobuf:"bytes,10,opt,name=failure_stack,json=failureStack,proto3" json:"failure_stack,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestFinished) Reset() {
	*x = TestFinished{}
	mi := &file_teov1_workers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestFinished) ProtoMessage() {}

func (x *TestFinished) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_workers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestFinished.ProtoReflect.Descriptor instead.
func (*TestFinished) Descriptor() ([]byte, []int) {
	return file_teov1_workers_proto_rawDescGZIP(), []int{7}
}

func (x *TestFinished) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *TestFinished) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TestFinished) GetTestPath() string {
	if x != nil {
		return x.TestPath
	}
	return ""
}

func (x *TestFinished) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *TestFinished) GetParamsHash() string {
	if x != nil {
		return x.ParamsHash
	}
	return ""
}

func (x *TestFinished) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TestFinished) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *TestFinished) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TestFinished) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *TestFinished) GetFailureStack() string {
	if x != nil {
		return x.FailureStack
	}
	return ""
}

type ShardFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // succeeded | failed | preempted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardFinished) Reset() {
	*x = ShardFinished{}
	mi := &file_teov1_workers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardFinished) ProtoMessage() {}

func (x *ShardFinished) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_workers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardFinished.ProtoReflect.Descriptor instead.
func (*ShardFinished) Descriptor() ([]byte, []int) {
	return file_teov1_workers_proto_rawDescGZIP(), []int{8}
}

func (x *ShardFinished) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardFinished) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ShardFinished) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_teov1_workers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_teov1_workers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_teov1_workers_proto_rawDescGZIP(), []int{9}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_teov1_workers_proto protoreflect.FileDescriptor

const file_teov1_workers_proto_rawDesc = "" +
	"\n" +
	"\x13teov1/workers.proto\x12\x06teo.v1\"\x90\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06runner\x18\x02 \x01(\tR\x06runner\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12#\n" +
	"\rcapacity_type\x18\x04 \x01(\tR\fcapacityType\"$\n" +
	"\x10RegisterResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\tR\x03ack\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\x13\n" +
	"\x11HeartbeatResponse\"L\n" +
	"\x15PullAssignmentRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06runner\x18\x02 \x01(\tR\x06runner\"\xc4\x01\n" +
	"\n" +
	"Assignment\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12$\n" +
	"\x0erepo_full_name\x18\x03 \x01(\tR\frepoFullName\x12*\n" +
	"\x05tests\x18\x04 \x03(\v2\x14.teo.v1.TestEntryRefR\x05tests\x122\n" +
	"\x15predicted_duration_ms\x18\x05 \x01(\x05R\x13predictedDurationMs\"W\n" +
	"\fTestEntryRef\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vparams_hash\x18\x03 \x01(\tR\n" +
	"paramsHash\"\xbe\x02\n" +
	"\fTestFinished\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1b\n" +
	"\ttest_path\x18\x03 \x01(\tR\btestPath\x12\x1b\n" +
	"\ttest_name\x18\x04 \x01(\tR\btestName\x12\x1f\n" +
	"\vparams_hash\x18\x05 \x01(\tR\n" +
	"paramsHash\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12\x18\n" +
	"\aoutcome\x18\a \x01(\tR\aoutcome\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x05R\n" +
	"durationMs\x12'\n" +
	"\x0ffailure_message\x18\t \x01(\tR\x0efailureMessage\x12#\n" +
	"\rfailure_stack\x18\n" +
	" \x01(\tR\ffailureStack\"Y\n" +
	"\rShardFinished\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xc3\x02\n" +
	"\aWorkers\x12=\n" +
	"\bRegister\x12\x17.teo.v1.RegisterRequest\x1a\x18.teo.v1.RegisterResponse\x12@\n" +
	"\tHeartbeat\x12\x18.teo.v1.HeartbeatRequest\x1a\x19.teo.v1.HeartbeatResponse\x12C\n" +
	"\x0ePullAssignment\x12\x1d.teo.v1.PullAssignmentRequest\x1a\x12.teo.v1.Assignment\x127\n" +
	"\x12ReportTestFinished\x12\x14.teo.v1.TestFinished\x1a\v.teo.v1.Ack\x129\n" +
	"\x13ReportShardFinished\x12\x15.teo.v1.ShardFinished\x1a\v.teo.v1.AckB3Z1github.com/teo-dev/teo/internal/proto/teov1;teov1b\x06proto3"

var (
	file_teov1_workers_proto_rawDescOnce sync.Once
	file_teov1_workers_proto_rawDescData []byte
)

func file_teov1_workers_proto_rawDescGZIP() []byte {
	file_teov1_workers_proto_rawDescOnce.Do(func() {
		file_teov1_workers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_teov1_workers_proto_rawDesc), len(file_teov1_workers_proto_rawDesc)))
	})
	return file_teov1_workers_proto_rawDescData
}

var file_teov1_workers_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_teov1_workers_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: teo.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: teo.v1.RegisterResponse
	(*HeartbeatRequest)(nil),      // 2: teo.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 3: teo.v1.HeartbeatResponse
	(*PullAssignmentRequest)(nil), // 4: teo.v1.PullAssignmentRequest
	(*Assignment)(nil),            // 5: teo.v1.Assignment
	(*TestEntryRef)(nil),          // 6: teo.v1.TestEntryRef
	(*TestFinished)(nil),          // 7: teo.v1.TestFinished
	(*ShardFinished)(nil),         // 8: teo.v1.ShardFinished
	(*Ack)(nil),                   // 9: teo.v1.Ack
}
var file_teov1_workers_proto_depIdxs = []int32{
	6, // 0: teo.v1.Assignment.tests:type_name -> teo.v1.TestEntryRef
	0, // 1: teo.v1.Workers.Register:input_type -> teo.v1.RegisterRequest
	2, // 2: teo.v1.Workers.Heartbeat:input_type -> teo.v1.HeartbeatRequest
	4, // 3: teo.v1.Workers.PullAssignment:input_type -> teo.v1.PullAssignmentRequest
	7, // 4: teo.v1.Workers.ReportTestFinished:input_type -> teo.v1.TestFinished
	8, // 5: teo.v1.Workers.ReportShardFinished:input_type -> teo.v1.ShardFinished
	1, // 6: teo.v1.Workers.Register:output_type -> teo.v1.RegisterResponse
	3, // 7: teo.v1.Workers.Heartbeat:output_type -> teo.v1.HeartbeatResponse
	5, // 8: teo.v1.Workers.PullAssignment:output_type -> teo.v1.Assignment
	9, // 9: teo.v1.Workers.ReportTestFinished:output_type -> teo.v1.Ack
	9, // 10: teo.v1.Workers.ReportShardFinished:output_type -> teo.v1.Ack
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_teov1_workers_proto_init() }
func file_teov1_workers_proto_init() {
	if File_teov1_workers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_teov1_workers_proto_rawDesc), len(file_teov1_workers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teov1_workers_proto_goTypes,
		DependencyIndexes: file_teov1_workers_proto_depIdxs,
		MessageInfos:      file_teov1_workers_proto_msgTypes,
	}.Build()
	File_teov1_workers_proto = out.File
	file_teov1_workers_proto_goTypes = nil
	file_teov1_workers_proto_depIdxs = nil
}
