// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: teov1/workers.proto

package teov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Workers_Register_FullMethodName            = "/teo.v1.Workers/Register"
	Workers_Heartbeat_FullMethodName           = "/teo.v1.Workers/Heartbeat"
	Workers_PullAssignment_FullMethodName      = "/teo.v1.Workers/PullAssignment"
	Workers_ReportTestFinished_FullMethodName  = "/teo.v1.Workers/ReportTestFinished"
	Workers_ReportShardFinished_FullMethodName = "/teo.v1.Workers/ReportShardFinished"
)

// WorkersClient is the client API for Workers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkersClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	PullAssignment(ctx context.Context, in *PullAssignmentRequest, opts ...grpc.CallOption) (*Assignment, error)
	ReportTestFinished(ctx context.Context, in *TestFinished, opts ...grpc.CallOption) (*Ack, error)
	ReportShardFinished(ctx context.Context, in *ShardFinished, opts ...grpc.CallOption) (*Ack, error)
}

type workersClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkersClient(cc grpc.ClientConnInterface) WorkersClient {
	return &workersClient{cc}
}

func (c *workersClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Workers_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workersClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Workers_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workersClient) PullAssignment(ctx context.Context, in *PullAssignmentRequest, opts ...grpc.CallOption) (*Assignment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assignment)
	err := c.cc.Invoke(ctx, Workers_PullAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workersClient) ReportTestFinished(ctx context.Context, in *TestFinished, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Workers_ReportTestFinished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workersClient) ReportShardFinished(ctx context.Context, in *ShardFinished, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Workers_ReportShardFinished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkersServer is the server API for Workers service.
// All implementations must embed UnimplementedWorkersServer
// for forward compatibility.
type WorkersServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	PullAssignment(context.Context, *PullAssignmentRequest) (*Assignment, error)
	ReportTestFinished(context.Context, *TestFinished) (*Ack, error)
	ReportShardFinished(context.Context, *ShardFinished) (*Ack, error)
	mustEmbedUnimplementedWorkersServer()
}

// UnimplementedWorkersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkersServer struct{}

func (UnimplementedWorkersServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWorkersServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkersServer) PullAssignment(context.Context, *PullAssignmentRequest) (*Assignment, error) {
	return nil, status.Error(codes.Unimplemented, "method PullAssignment not implemented")
}
func (UnimplementedWorkersServer) ReportTestFinished(context.Context, *TestFinished) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTestFinished not implemented")
}
func (UnimplementedWorkersServer) ReportShardFinished(context.Context, *ShardFinished) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportShardFinished not implemented")
}
func (UnimplementedWorkersServer) mustEmbedUnimplementedWorkersServer() {}
func (UnimplementedWorkersServer) testEmbeddedByValue()                 {}

// UnsafeWorkersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkersServer will
// result in compilation errors.
type UnsafeWorkersServer interface {
	mustEmbedUnimplementedWorkersServer()
}

func RegisterWorkersServer(s grpc.ServiceRegistrar, srv WorkersServer) {
	// If the following call panics, it indicates UnimplementedWorkersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Workers_ServiceDesc, srv)
}

func _Workers_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workers_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workers_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workers_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workers_PullAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServer).PullAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workers_PullAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServer).PullAssignment(ctx, req.(*PullAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workers_ReportTestFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestFinished)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServer).ReportTestFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workers_ReportTestFinished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServer).ReportTestFinished(ctx, req.(*TestFinished))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workers_ReportShardFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardFinished)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServer).ReportShardFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workers_ReportShardFinished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServer).ReportShardFinished(ctx, req.(*ShardFinished))
	}
	return interceptor(ctx, in, info, handler)
}

// Workers_ServiceDesc is the grpc.ServiceDesc for Workers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Workers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teo.v1.Workers",
	HandlerType: (*WorkersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Workers_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Workers_Heartbeat_Handler,
		},
		{
			MethodName: "PullAssignment",
			Handler:    _Workers_PullAssignment_Handler,
		},
		{
			MethodName: "ReportTestFinished",
			Handler:    _Workers_ReportTestFinished_Handler,
		},
		{
			MethodName: "ReportShardFinished",
			Handler:    _Workers_ReportShardFinished_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teov1/workers.proto",
}
